/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        leaf: {
          DEFAULT: '#2E9E4F',
          50: '#F0FDF4',
          100: '#DCFCE7',
          200: '#BBF7D0',
          300: '#86EFAC',
          400: '#4ADE80',
          500: '#2E9E4F',
          600: '#237D3E',
          700: '#195E2E',
          800: '#14532D',
          900: '#0F3C20',
        },
        forest: '#14532D',
        sky: {
          DEFAULT: '#38BDF8',
          50: '#F0F9FF',
          100: '#E0F2FE',
          200: '#BAE6FD',
          300: '#7DD3FC',
          400: '#38BDF8',
          500: '#0EA5E9',
          600: '#0284C7',
          700: '#0369A1',
        },
        sun: {
          DEFAULT: '#FBBF24',
          50: '#FFFBEB',
          100: '#FEF3C7',
          200: '#FDE68A',
          300: '#FCD34D',
          400: '#FBBF24',
          500: '#F59E0B',
          600: '#D97706',
        },
        warm: '#FFFDF7',
        mint: '#F0FDF4',
        critical: '#EF4444',

        // Landing design system tokens
        "primary": "#006b2d",
        "primary-container": "#04873b",
        "primary-fixed": "#8cfa9f",
        "primary-fixed-dim": "#70dd85",
        "on-primary": "#ffffff",
        "on-primary-container": "#f7fff3",
        "on-primary-fixed": "#002109",
        "on-primary-fixed-variant": "#005321",
        "secondary": "#2e6a41",
        "secondary-container": "#b1f2be",
        "secondary-fixed": "#b1f2be",
        "secondary-fixed-dim": "#96d5a3",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#347047",
        "on-secondary-fixed": "#00210d",
        "on-secondary-fixed-variant": "#12512c",
        "tertiary": "#006387",
        "tertiary-container": "#007da9",
        "tertiary-fixed": "#c4e7ff",
        "tertiary-fixed-dim": "#7bd0ff",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#fcfcff",
        "on-tertiary-fixed": "#001e2c",
        "on-tertiary-fixed-variant": "#004c69",
        "surface": "#f8f9ff",
        "surface-dim": "#ccdbf4",
        "surface-bright": "#f8f9ff",
        "surface-variant": "#d5e3fd",
        "surface-tint": "#006e2e",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff4ff",
        "surface-container": "#e6eeff",
        "surface-container-high": "#dde9ff",
        "surface-container-highest": "#d5e3fd",
        "on-surface": "#0d1c2f",
        "on-surface-variant": "#3e4a3e",
        "inverse-surface": "#233144",
        "inverse-on-surface": "#ebf1ff",
        "inverse-primary": "#70dd85",
        "background": "#f8f9ff",
        "on-background": "#0d1c2f",
        "outline": "#6e7a6d",
        "outline-variant": "#bdcabb",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.25rem",
        "gutter": "1rem",
        "gutter-desktop": "1.5rem",
        "margin": "1rem",
        "margin-desktop": "2.5rem",
        "margin-tablet": "1.5rem",
      },
      fontSize: {
        "headline-xl": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "headline-xl-mobile": ["30px", { "lineHeight": "38px", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "headline-md": ["22px", { "lineHeight": "30px", "fontWeight": "700" }],
        "headline-sm": ["18px", { "lineHeight": "26px", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "label-lg": ["15px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600" }],
        "label-md": ["13px", { "lineHeight": "18px", "letterSpacing": "0.02em", "fontWeight": "600" }],
        "label-sm": ["11px", { "lineHeight": "16px", "letterSpacing": "0.04em", "fontWeight": "700" }],
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        heading: ['"Plus Jakarta Sans"', 'Poppins', 'sans-serif'],
        "headline-xl": ['"Plus Jakarta Sans"', 'sans-serif'],
        "headline-lg": ['"Plus Jakarta Sans"', 'sans-serif'],
        "headline-md": ['"Plus Jakarta Sans"', 'sans-serif'],
        "headline-sm": ['"Plus Jakarta Sans"', 'sans-serif'],
        "body-lg": ['"Plus Jakarta Sans"', 'sans-serif'],
        "body-md": ['"Plus Jakarta Sans"', 'sans-serif'],
        "body-sm": ['"Plus Jakarta Sans"', 'sans-serif'],
        "label-lg": ['"Plus Jakarta Sans"', 'sans-serif'],
        "label-md": ['"Plus Jakarta Sans"', 'sans-serif'],
        "label-sm": ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      boxShadow: {
        card: '0 2px 12px -2px rgba(20, 83, 45, 0.06), 0 4px 16px -4px rgba(20, 83, 45, 0.04)',
        hover: '0 8px 24px -4px rgba(20, 83, 45, 0.1), 0 4px 12px -2px rgba(20, 83, 45, 0.06)',
        highlight: '0 0 0 4px rgba(251, 191, 36, 0.45)',
      },
      borderRadius: {
        '2xl': '1rem',
        '3xl': '1.5rem',
      },
      animation: {
        'pulse-subtle': 'pulseSubtle 2.5s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'pulse-glow': 'pulseGlow 2.5s ease-in-out infinite',
      },
      keyframes: {
        pulseSubtle: {
          '0%, 100%': { opacity: '1', transform: 'scale(1)' },
          '50%': { opacity: '0.85', transform: 'scale(1.02)' },
        },
        pulseGlow: {
          '0%, 100%': { boxShadow: '0 0 0 0 rgba(251, 191, 36, 0.6)' },
          '50%': { boxShadow: '0 0 0 8px rgba(251, 191, 36, 0)' },
        },
      },
    },
  },
  plugins: [],
}
